### ISSUE TITLE
Thank you + Question

### ISSUE THREAD

**Issue by gabrielwoj** [ManlyMarco/IllusionSFW#1]
_**Before I write my message, I just want to apologize for posting this on GitHub as an "Issue". I tried posting this on one of your Youtube videos, but Youtube was deleting my comment soon after posting it. Youtube sometimes do that when it finds a word it doesn't like, but it doesn't actually tell me what the word was, so I had no choice than to go here.**_

Hi, I just want to say thank you for making the KK SFW plugin. I'm not really sure how I found this game/tool, but I really liked the idea of a character creator and scene creator, but I wasn't sure in buying and using it due to the NSFW stuff. I don't think too many people thank you for this, but I really appreciate your work and time dedication in making this plugin, I appreciate it a lot.

I'm going to buy the game soon, and maybe the DLC that is on Steam too (since it adds a lot of other customizable stuff). My only worry is if the community-made stuff (mods) have that sort of Non-SFW stuff in it. I got the "KK HF Patch", so I can get all the other extras along with the SFW plugin. Even if I install those, would the SFW mod hide them? Based on this repository's README, it apparently also disables mods.

This question is only for Koikatsu, and not the other Illusion games/tools, but I imagine it applies to all of them.

Thanks.

**Comment by ManlyMarco** [comment]
Hello! Yes, this plugin will disable most NSFW mods, but some might slip through, in those cases you can right click the offending item in the list and hide it (in character maker). This plugin only works for Koikatsu.
